version: '2.1'

services:
  b1:
    build: ./images/bgp/.
    volumes:
      - ./volumes/bgp/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisord.conf:ro
    image: bgp:20180508
    privileged: true
    ports:
      #admin
      - "10101:2601"
      #ospf
      - "10002:2604"
      #bgp
      - "10103:2605"
    networks:
      dns_net:
        ipv4_address: 200.17.18.2
      k8_net:
        ipv4_address: 200.17.18.130
      loop_net:
        ipv4_address: 200.17.19.2
      ext_net:
        ipv4_address: 70.0.0.10
  
  host1:
    build: ./images/host/.
    image: alpine:20190106
    command: top
    privileged: true
    networks:
      loop_net:
        ipv4_address: 200.17.19.10

  dns_server:
    image: sameersbn/bind:latest
    dns: 8.8.8.8
    volumes:
      - ./volumes/dns/data:/data
    environment:
      - ROOT_PASSWORD=SecretPassword
    privileged: true
    ports:
        - 10000:10000
        - "200.17.18.1:53:53/udp"
        - "200.17.18.1:53:53/tcp"
    networks:
      dns_net:
        ipv4_address: 200.17.18.3

networks:
  dns_net:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 200.17.18.0/25
  k8_net:
    internal: true
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 200.17.18.128/25
  loop_net:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 200.17.19.0/26
  ext_net:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 70.0.0.0/24