apiVersion: v1
kind: Service
metadata:
  name: {{ include "strapi.name" . }}-svc
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Chart.Name }}
  selector:
    app.kubernetes.io/name: {{ include "strapi.name" . }}
