---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strapi-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: guilletrejo/strapi_address:latest
        env:
          - name: APP_NAME
            value: strapi-app
          - name: DATABASE_CLIENT
            value: mongo
          - name: DATABASE_HOST
            value: mongo-svc
          - name: DATABASE_PORT
            value: "27017"
          - name: DATABASE_NAME
            value: strapi
        ports:
          - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-svc
  labels:
    app: strapi
spec:
  ports:
  - port: 1337
    name: strapi
  selector:
    app: strapi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: a.efn.unc.edu.ar
    http:
      paths:
        - path: /
          backend:
            serviceName: strapi-svc
            servicePort: 1337
