# Default values for strapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: "1"

imageS:
  repository: guilletrejo/strapi_address
  tag: latest
  port: 1337

imageM:
  repository: mongo
  port: 27017

service:
  port: 1337

ingress:
  host: strapi.a.efn.unc.edu.ar
  port: 1337
